import chalk from "chalk";
import { Command } from "commander";
import ora from "ora";
import { apiRequest, BASE_URL } from "../utils/api";
import { loadProjectConfig } from "../utils/config";
import { exitWithError, isAgentMode, requireAuth } from "../utils/output";

interface ApiKeyResponse {
  success: boolean;
  apiKey: string;
}

interface ApiKeyOptions {
  name?: string;
  output?: string;
}

export const apiKeyCommand = new Command("api-key")
  .description(
    "Generate an API key for the linked organization. Use it in CI with COMMET_API_KEY env var.",
  )
  .option("--name <name>", "Name for the API key", "CLI")
  .option(
    "--output <format>",
    "Output format: human (default) or agent",
    "human",
  )
  .addHelpText(
    "after",
    `
Examples:
  $ commet api-key                    Generate a key for the linked org
  $ commet api-key --name "GitHub CI" Name it for easy identification
  $ commet api-key --output agent     JSON output with the key

Then use it in CI:
  $ COMMET_API_KEY=ck_... commet push --yes
`,
  )
  .action(async (options: ApiKeyOptions) => {
    const agentMode = isAgentMode(options);

    if (agentMode) {
      console.log(
        JSON.stringify({
          deprecated: true,
          replacement: "commet api-keys create",
        }),
      );
    } else {
      console.log(
        chalk.yellow("⚠ Deprecated: use 'commet api-keys create' instead"),
      );
    }

    if (process.env.COMMET_API_KEY) {
      exitWithError({
        code: "invalid_context",
        message: "Cannot create API keys while using COMMET_API_KEY",
        action: "commet login",
      });
    }

    requireAuth();

    const projectConfig = loadProjectConfig();
    if (!projectConfig) {
      exitWithError({
        code: "project_not_linked",
        message: "No organization linked",
        action: "commet link",
      });
    }

    const spinner = agentMode ? null : ora("Generating API key...").start();

    const result = await apiRequest<ApiKeyResponse>(
      `${BASE_URL}/api/cli/api-keys`,
      {
        method: "POST",
        body: JSON.stringify({
          organizationId: projectConfig.orgId,
          name: options.name,
        }),
      },
    );

    if (result.error || !result.data) {
      if (agentMode) {
        console.log(JSON.stringify({ error: result.error }));
      } else {
        spinner?.fail("Failed to create API key");
        console.error(chalk.red("Error:"), result.error?.message);
      }
      process.exit(1);
    }

    const { apiKey } = result.data;
    const isLive = projectConfig.mode === "live";

    if (agentMode) {
      console.log(
        JSON.stringify({
          success: true,
          apiKey,
          mode: projectConfig.mode,
          ...(isLive
            ? {
                warning:
                  "This is a live API key. Rotate it before using in production if generated by an agent.",
              }
            : {}),
        }),
      );
      return;
    }

    spinner?.succeed("API key created");
    console.log("");
    console.log(`  ${chalk.bold(apiKey)}`);
    console.log("");
    console.log(chalk.yellow("  ⚠ This key is shown only once — copy it now."));
    if (isLive) {
      console.log(
        chalk.yellow(
          "  ⚠ This is a live key. Rotate it from the dashboard before production use.",
        ),
      );
    }
    console.log(
      chalk.dim("\n  Use in CI: COMMET_API_KEY=<key> commet push --yes"),
    );
  });
