interface EventType {
  code: string;
  name: string;
  description?: string;
}

interface SeatType {
  code: string;
  name: string;
  description?: string;
  isFree: boolean;
}

interface Product {
  publicId: string;
  name: string;
  description?: string;
}

export function generateTypes(
  eventTypes: EventType[],
  seatTypes: SeatType[],
  products: Product[],
): string {
  // Generate event type union
  const eventTypeUnion =
    eventTypes.length > 0
      ? eventTypes.map((e) => `"${e.code}"`).join(" | ")
      : "string";

  // Generate seat type union
  const seatTypeUnion =
    seatTypes.length > 0
      ? seatTypes.map((s) => `"${s.code}"`).join(" | ")
      : "string";

  // Generate product type union
  const productTypeUnion =
    products.length > 0
      ? products.map((p) => `"${p.publicId}"`).join(" | ")
      : "string";

  // Generate detailed comments
  const eventComments = eventTypes
    .map(
      (e) =>
        ` * - "${e.code}": ${e.name}${e.description ? ` - ${e.description}` : ""}`,
    )
    .join("\n");

  const seatComments = seatTypes
    .map(
      (s) =>
        ` * - "${s.code}": ${s.name}${s.description ? ` - ${s.description}` : ""} ${s.isFree ? "(Free)" : ""}`,
    )
    .join("\n");

  const productComments = products
    .map(
      (p) =>
        ` * - "${p.publicId}": ${p.name}${p.description ? ` - ${p.description}` : ""}`,
    )
    .join("\n");

  return `// Auto-generated by Commet CLI
// Do not edit this file manually - run 'commet pull' to update

/**
 * This augments the Commet SDK to automatically use your organization's
 * specific event types, seat types, and products without requiring generic type parameters.
 * 
 * Event types available in your organization:
${eventComments || " * (none)"}
 * 
 * Seat types available in your organization:
${seatComments || " * (none)"}
 * 
 * Products available in your organization:
${productComments || " * (none)"}
 * 
 */ 
declare module '@commet/node' {
  interface CommetGeneratedTypes {
    eventType: ${eventTypeUnion};
    seatType: ${seatTypeUnion};
    productId: ${productTypeUnion};
  }
}

// This export is required for TypeScript to treat this file as a module
// and apply the module augmentation above
export {};
`;
}
