interface EventType {
  code: string;
  name: string;
  description?: string;
}

interface SeatType {
  code: string;
  name: string;
  description?: string;
  isFree: boolean;
}

interface Feature {
  code: string;
  name: string;
  description?: string;
  type: string;
}

interface Plan {
  code: string;
  name: string;
  description?: string;
}

export function generateTypes(
  eventTypes: EventType[],
  seatTypes: SeatType[],
  features: Feature[],
  plans: Plan[],
): string {
  // Generate event type union
  const eventTypeUnion =
    eventTypes.length > 0
      ? eventTypes.map((e) => `"${e.code}"`).join(" | ")
      : "string";

  // Generate seat type union
  const seatTypeUnion =
    seatTypes.length > 0
      ? seatTypes.map((s) => `"${s.code}"`).join(" | ")
      : "string";

  // Generate plan code union
  const planCodeUnion =
    plans.length > 0 ? plans.map((p) => `"${p.code}"`).join(" | ") : "string";

  // Generate feature code union
  const featureCodeUnion =
    features.length > 0
      ? features.map((f) => `"${f.code}"`).join(" | ")
      : "string";

  // Generate detailed comments
  const eventComments = eventTypes
    .map(
      (e) =>
        ` * - "${e.code}": ${e.name}${e.description ? ` - ${e.description}` : ""}`,
    )
    .join("\n");

  const seatComments = seatTypes
    .map(
      (s) =>
        ` * - "${s.code}": ${s.name}${s.description ? ` - ${s.description}` : ""} ${s.isFree ? "(Free)" : ""}`,
    )
    .join("\n");

  const planComments = plans
    .map(
      (p) =>
        ` * - "${p.code}": ${p.name}${p.description ? ` - ${p.description}` : ""}`,
    )
    .join("\n");

  const featureComments = features
    .map(
      (f) =>
        ` * - "${f.code}": ${f.name} (${f.type})${f.description ? ` - ${f.description}` : ""}`,
    )
    .join("\n");

  return `// Auto-generated by Commet CLI
// Do not edit this file manually - run 'commet pull' to update

/**
 * This augments the Commet SDK to automatically use your organization's
 * specific event types, seat types, plans, and features without requiring generic type parameters.
 * 
 * Event types available in your organization:
${eventComments || " * (none)"}
 * 
 * Seat types available in your organization:
${seatComments || " * (none)"}
 * 
 * Plans available in your organization:
${planComments || " * (none)"}
 * 
 * Features available in your organization:
${featureComments || " * (none)"}
 * 
 */ 
declare module '@commet/node' {
  interface CommetGeneratedTypes {
    eventType: ${eventTypeUnion};
    seatType: ${seatTypeUnion};
    planCode: ${planCodeUnion};
    featureCode: ${featureCodeUnion};
  }
}

// This export is required for TypeScript to treat this file as a module
// and apply the module augmentation above
export {};
`;
}
