interface SeatType {
  code: string;
  name: string;
  description?: string;
  isFree: boolean;
}

interface Feature {
  code: string;
  name: string;
  description?: string;
  type: string;
}

interface Plan {
  code: string;
  name: string;
  description?: string;
}

export function generateTypes(
  seatTypes: SeatType[],
  features: Feature[],
  plans: Plan[],
): string {
  const seatTypeUnion =
    seatTypes.length > 0
      ? seatTypes.map((s) => `"${s.code}"`).join(" | ")
      : "string";

  const planCodeUnion =
    plans.length > 0 ? plans.map((p) => `"${p.code}"`).join(" | ") : "string";

  const featureCodeUnion =
    features.length > 0
      ? features.map((f) => `"${f.code}"`).join(" | ")
      : "string";

  const seatComments = seatTypes
    .map(
      (s) =>
        ` * - "${s.code}": ${s.name}${s.description ? ` - ${s.description}` : ""} ${s.isFree ? "(Free)" : ""}`,
    )
    .join("\n");

  const planComments = plans
    .map(
      (p) =>
        ` * - "${p.code}": ${p.name}${p.description ? ` - ${p.description}` : ""}`,
    )
    .join("\n");

  const featureComments = features
    .map(
      (f) =>
        ` * - "${f.code}": ${f.name} (${f.type})${f.description ? ` - ${f.description}` : ""}`,
    )
    .join("\n");

  return `// Auto-generated by Commet CLI
// Do not edit this file manually - run 'commet pull' to update

/**
 * This augments the Commet SDK with your organization's
 * feature codes, seat types, and plan codes for autocomplete.
 *
 * Features available in your organization:
${featureComments || " * (none)"}
 *
 * Seat types available in your organization:
${seatComments || " * (none)"}
 *
 * Plans available in your organization:
${planComments || " * (none)"}
 *
 */
declare module '@commet/node' {
  interface CommetGeneratedTypes {
    seatType: ${seatTypeUnion};
    planCode: ${planCodeUnion};
    featureCode: ${featureCodeUnion};
  }
}

export {};
`;
}
