// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

import type { ApiResponse, RequestOptions } from "../types/common";
import type { FeatureType } from "../types/enums";
import type {
  DeletedObject,
  Feature,
  FeatureAccess,
  FeatureLookup,
} from "../types/models";
import type { CommetHTTPClient } from "../utils/http";

export interface ListFeaturesParams {
  customerId: string;
}

export interface GetFeatureAccessParams {
  code: string;
  customerId: string;
  action?: string;
}

export interface CanUseFeatureParams {
  code: string;
  customerId: string;
}

export interface CreateFeatureParams {
  name: string;
  code: string;
  type: FeatureType;
  description?: string;
  unitName?: string;
}

export interface UpdateFeatureParams {
  code: string;
  name?: string;
  description?: string | null;
  unitName?: string | null;
}

export interface DeleteFeatureParams {
  code: string;
}

export class FeaturesResource {
  constructor(private httpClient: CommetHTTPClient) {}

  /** List all features for a customer's active subscription. */
  async list(
    params: ListFeaturesParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Array<FeatureAccess>>> {
    return this.httpClient.get("/features", params, options);
  }

  /** Get feature access details. Use action=canUse to check if customer can consume one more unit. */
  async get(
    params: GetFeatureAccessParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<FeatureLookup>> {
    const { code, ...rest } = params;
    return this.httpClient.get(`/features/${code}`, rest, options);
  }

  /** Get feature access details. Use action=canUse to check if customer can consume one more unit. */
  async canUse(
    params: CanUseFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<FeatureLookup>> {
    const { code, ...rest } = params;
    return this.httpClient.get(
      `/features/${code}`,
      { ...rest, action: "canUse" },
      options,
    );
  }

  /** Create a new feature. Code must be lowercase alphanumeric with underscores. */
  async create(
    params: CreateFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Feature>> {
    return this.httpClient.post("/features/manage", params, options);
  }

  /** Update a feature's name, description, or unit name. At least one field must be provided. */
  async update(
    params: UpdateFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Feature>> {
    const { code, ...rest } = params;
    return this.httpClient.put(`/features/${code}/manage`, rest, options);
  }

  /** Delete a feature. Fails if the feature is attached to active plans or has an active add-on. */
  async delete(
    params: DeleteFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<DeletedObject>> {
    const { code } = params;
    return this.httpClient.delete(
      `/features/${code}/manage`,
      undefined,
      options,
    );
  }
}
