// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

import type { ApiResponse, RequestOptions } from "../types/common";
import type {
  BillingInterval,
  ConsumptionModel,
  DiscountType,
} from "../types/enums";
import type {
  DefaultPlanPrice,
  DeletedObject,
  DeletedPlanRegionalPricing,
  Plan,
  PlanFeature,
  PlanPrice,
  PlanRegionalPricing,
  PlanRegionalPricingResult,
  PlanVisibility,
  RemovedPlanFeature,
} from "../types/models";
import type { CommetHTTPClient } from "../utils/http";

export interface ListPlansParams {
  includePrivate?: "true" | "false";
}

export interface GetPlanParams {
  id: string;
}

export interface CreatePlanParams {
  name: string;
  code: string;
  description?: string;
  consumptionModel?: ConsumptionModel;
  isPublic?: boolean;
  isFree?: boolean;
  blockOnExhaustion?: boolean;
  planGroupId?: string;
  metadata?: Record<string, unknown>;
}

export interface UpdatePlanParams {
  id: string;
  name?: string;
  description?: string | null;
  metadata?: Record<string, unknown>;
  isPublic?: boolean;
}

export interface DeletePlanParams {
  id: string;
}

export interface SetPlanVisibilityParams {
  id: string;
  isPublic: boolean;
}

export interface AddPlanFeatureParams {
  id: string;
  featureId: string;
  enabled?: boolean;
  includedAmount?: number;
  unlimited?: boolean;
  overage?: {
    enabled: boolean;
    unitPrice: number;
  };
  creditsPerUnit?: number | null;
  pricingMode?: "fixed" | "ai_model";
  margin?: number | null;
}

export interface UpdatePlanFeatureParams {
  id: string;
  featureId: string;
  enabled?: boolean;
  includedAmount?: number;
  unlimited?: boolean;
  overage?: {
    enabled?: boolean;
    unitPrice?: number;
  };
  creditsPerUnit?: number | null;
}

export interface RemovePlanFeatureParams {
  id: string;
  featureId: string;
}

export interface AddPlanPriceParams {
  id: string;
  billingInterval: BillingInterval;
  price: number;
  trialDays?: number;
  isDefault?: boolean;
  includedBalance?: number | null;
  includedCredits?: number | null;
  introOffer?: {
    enabled: boolean;
    discountType?: DiscountType | null;
    discountValue?: number | null;
    durationCycles?: number | null;
  };
}

export interface UpdatePlanPriceParams {
  id: string;
  priceId: string;
  price?: number;
  isDefault?: boolean;
  trialDays?: number;
  includedBalance?: number | null;
  includedCredits?: number | null;
  introOffer?: {
    enabled?: boolean;
    discountType?: DiscountType | null;
    discountValue?: number | null;
    durationCycles?: number | null;
  };
}

export interface DeletePlanPriceParams {
  id: string;
  priceId: string;
}

export interface SetDefaultPlanPriceParams {
  id: string;
  priceId: string;
}

export interface UpsertRegionalPricesParams {
  id: string;
  priceId: string;
  overrides: Array<{
    currency: string;
    price: number;
    includedBalance?: number;
  }>;
}

export interface SetPlanRegionalPricingParams {
  id: string;
  currency:
    | "ars"
    | "brl"
    | "clp"
    | "cop"
    | "pen"
    | "uyu"
    | "pyg"
    | "bob"
    | "mxn"
    | "cad"
    | "eur"
    | "jpy"
    | "cny"
    | "krw"
    | "hkd"
    | "sgd"
    | "twd"
    | "inr"
    | "thb";
  exchangeRate: number;
  prices?: Array<{
    priceId: string;
    price: number;
    includedBalance?: number;
  }>;
  features?: Array<{
    featureId: string;
    overageUnitPrice: number;
  }>;
  introOffers?: Array<{
    priceId: string;
    discountType: DiscountType;
    discountValue: number;
    durationCycles: number;
  }>;
}

export interface DeleteRegionalPricesParams {
  id: string;
  priceId: string;
}

export class PlansResource {
  constructor(private httpClient: CommetHTTPClient) {}

  /** List all plans with their prices and features. Optionally include private plans. */
  async list(
    params?: ListPlansParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Array<Plan>>> {
    return this.httpClient.get("/plans", params, options);
  }

  /** Get detailed plan information by code or ID. */
  async get(
    params: GetPlanParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Plan>> {
    const { id } = params;
    return this.httpClient.get(`/plans/${id}`, undefined, options);
  }

  /** Create a new plan with optional consumption model, visibility, and plan group assignment. */
  async create(
    params: CreatePlanParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Plan>> {
    return this.httpClient.post("/plans/manage", params, options);
  }

  /** Update a plan's name, description, visibility, or metadata. */
  async update(
    params: UpdatePlanParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<Plan>> {
    const { id, ...rest } = params;
    return this.httpClient.put(`/plans/${id}/manage`, rest, options);
  }

  /** Soft-delete a plan. */
  async delete(
    params: DeletePlanParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<DeletedObject>> {
    const { id } = params;
    return this.httpClient.delete(`/plans/${id}/manage`, undefined, options);
  }

  /** Toggle a plan between public and private. */
  async setVisibility(
    params: SetPlanVisibilityParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanVisibility>> {
    const { id, ...rest } = params;
    return this.httpClient.put(`/plans/${id}/visibility`, rest, options);
  }

  /** Attach a feature to a plan with limits, overage, and credits configuration. */
  async addFeature(
    params: AddPlanFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanFeature>> {
    const { id, ...rest } = params;
    return this.httpClient.post(`/plans/${id}/features`, rest, options);
  }

  /** Update limits, overage, or enabled status of a feature on a plan. */
  async updateFeature(
    params: UpdatePlanFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanFeature>> {
    const { id, featureId, ...rest } = params;
    return this.httpClient.put(
      `/plans/${id}/features/${featureId}`,
      rest,
      options,
    );
  }

  /** Detach a feature from a plan. */
  async removeFeature(
    params: RemovePlanFeatureParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<RemovedPlanFeature>> {
    const { id, featureId } = params;
    return this.httpClient.delete(
      `/plans/${id}/features/${featureId}`,
      undefined,
      options,
    );
  }

  /** Add a billing interval price to a plan with optional trial days and included balance/credits. */
  async addPrice(
    params: AddPlanPriceParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanPrice>> {
    const { id, ...rest } = params;
    return this.httpClient.post(`/plans/${id}/prices`, rest, options);
  }

  /** Update an existing price on a plan. */
  async updatePrice(
    params: UpdatePlanPriceParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanPrice>> {
    const { id, priceId, ...rest } = params;
    return this.httpClient.put(`/plans/${id}/prices/${priceId}`, rest, options);
  }

  /** Remove a price from a plan. */
  async deletePrice(
    params: DeletePlanPriceParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<DeletedObject>> {
    const { id, priceId } = params;
    return this.httpClient.delete(
      `/plans/${id}/prices/${priceId}`,
      undefined,
      options,
    );
  }

  /** Set a specific price as the default for its plan. Unsets previous default. */
  async setDefaultPrice(
    params: SetDefaultPlanPriceParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<DefaultPlanPrice>> {
    const { id, priceId } = params;
    return this.httpClient.put(
      `/plans/${id}/prices/${priceId}/default`,
      {},
      options,
    );
  }

  /** Create or update regional currency price overrides for a plan price. */
  async setRegionalPrices(
    params: UpsertRegionalPricesParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanRegionalPricing>> {
    const { id, priceId, ...rest } = params;
    return this.httpClient.put(
      `/plans/${id}/prices/${priceId}/regional`,
      rest,
      options,
    );
  }

  /** Configure a plan's regional pricing for one currency. Sending only currency and exchangeRate derives every regional value (base price, included balance, feature overage, intro offer) from the USD value at that rate. Optional per-price and per-feature overrides are stored as manual values. */
  async setRegionalPricing(
    params: SetPlanRegionalPricingParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<PlanRegionalPricingResult>> {
    const { id, ...rest } = params;
    return this.httpClient.put(`/plans/${id}/regional`, rest, options);
  }

  /** Remove all regional currency overrides for a plan price. */
  async deleteRegionalPrices(
    params: DeleteRegionalPricesParams,
    options?: RequestOptions,
  ): Promise<ApiResponse<DeletedPlanRegionalPricing>> {
    const { id, priceId } = params;
    return this.httpClient.delete(
      `/plans/${id}/prices/${priceId}/regional`,
      undefined,
      options,
    );
  }
}
