name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC trusted publishing
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Update npm (required for trusted publishing)
        run: npm install -g npm@latest
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Type check
        run: pnpm typecheck
        
      - name: Build package
        run: pnpm build
        
      - name: Verify package contents
        run: |
          echo "Package contents:"
          ls -lah dist/
          echo "Checking required files..."
          if [ ! -f "dist/index.js" ] || [ ! -f "dist/index.mjs" ] || [ ! -f "dist/index.d.ts" ]; then
            echo "Error: Required build files not found"
            exit 1
          fi
        
      - name: Publish to npm (with trusted publishing)
        run: pnpm publish --access public --no-git-checks --provenance
          
      - name: Create publish summary
        run: |
          echo "✅ Package published successfully!" >> $GITHUB_STEP_SUMMARY
          echo "📦 Package: commet@$(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
          echo "🔗 View on NPM: https://www.npmjs.com/package/commet" >> $GITHUB_STEP_SUMMARY

